### ISSUE TITLE
Support for non-Steam games added to Steam client

### ISSUE THREAD

**Issue by mtkennerly** [WilliamVenner/steamlocate-rs#12]
Hi! Do you think it would make sense to support listing games added to Steam via the "add a non-Steam game" option? I'm using steamlocate in [Ludusavi](https://github.com/mtkennerly/ludusavi), and I got [a feature request](https://github.com/mtkennerly/ludusavi/issues/130) to look up Proton save data for such games. It requires knowing the configured target path and app name, then calculating the stand-in app ID used for the Proton compatdata subfolder ([sample code](https://blog.yo1.dog/calculate-id-for-non-steam-games-js/)). The info is stored in `<steam>/userdata/<user>/config/shortcuts.vdf`.

I was imagining something like this:

```rust
let mut steam = steamlocate::SteamDir::locate()?;
let id = steam.shortcut("Game Name")?.id();
let shortcuts = steam.shortcuts()?;
```

**Comment by LovecraftianHorror** [comment]
I'll dig into things this weekend

**Comment by LovecraftianHorror** [comment]
Sorry for the delay, life and all

Had some time today to look into this issue. The `shortcuts.vdf` is stored using the binary VDF format instead of the text format (yes they both use the same extension :upside_down_face:)

Unfortunately I don't know of any existing implementation for parsing binary VDF in Rust. I have plans to add support in `keyvalues-parser`, but that certainly won't be any time soon (will likely switch from `pest` -> `nom` first, so that both impls use the same parsing library). All that being said this is looking like it will be in the month+ category for having this issue resolved :/

**Comment by mtkennerly** [comment]
No worries, that's understandable.

This is probably hackier than you'd be interested in using as a reference/stopgap, but SteamGrid has some Go code that parses it with regex 😅 https://github.com/boppreh/steamgrid/blob/36f069ef2a9bb0b1f0f0af7e17fa1d8bd68e627c/games.go#L100-L137

**Comment by LovecraftianHorror** [comment]
Gotta love comments like this lol

```go
// The actual binary format is known, but using regexes is way easier than
// parsing the entire file. If I run into any problems I'll replace this.
```

Thanks for the reference! I think it could certainly work fine as an easy-to-implement stopgap that can be used till proper binary parsing is all handled
