### ISSUE TITLE
[Question] why does this depend on two separate vdf parsers?

### ISSUE THREAD

**Issue by Narcha** [WilliamVenner/steamlocate-rs#28]
What the title says. What justifies the use of both `steamy-vdf` and `keyvalues-parser`/`keyvalues-serde`?

**Comment by CosmicHorrorDev** [comment]
Apologies for the late reply. Must have missed the initial notification

Originally this crate used `steamy-vdf`; however, there have been some issues where it failed to parse some valid files (e.g. https://github.com/meh/steamy/issues/1). For this reason part, but not all, of the parsing was moved over to `keyvalues-parser`

It will be moved to only use `keyvalues-parser`/`keyvalues-serde` for the v2 release, but that also involves more-or-less a total rewrite of this crate, so that's still been in progress since I'm very short on time these days. If you don't want to pull in both parsers then you can just use the `2.0.0-alpha.0` release on crates.io which only uses `keyvalues-parser`/`keyvalues-serde`

**Comment by Narcha** [comment]
I see. Thanks!
